import { Link, useLocation } from "wouter";
import { Activity, ArrowLeft, ArrowUpRight, BarChart3, BookOpen, BrainCircuit, ChevronRight, CircleHelp, Code2, Crosshair, Database, FileText, Gauge, Layers3, LockKeyhole, Network, Plus, Search, Settings2, ShieldCheck, Terminal, Trophy, Users, Zap, type LucideIcon } from "lucide-react";
import { toast } from "sonner";

// RHZ LAB SectionPage: Graphite Control Room surfaces, amber active signal, technical UI labels.

type SectionConfig = { title: string; eyebrow: string; description: string; icon: LucideIcon; stats: [string, string][]; tabs: string[]; cards: { icon: LucideIcon; title: string; type: string; meta: string; tone: "amber" | "cyan" | "green" | "steel"; }[] };

const iconMap = { Dashboard: Gauge, Learn: BookOpen, Challenges: Crosshair, Labs: Database, Machines: Network, Academy: BrainCircuit, Paths: Layers3, Leaderboard: Trophy, Terminal, Notes: FileText, Bookmarks: LockKeyhole };
const configs: Record<string, SectionConfig> = {
  learn: { title: "Learn", eyebrow: "LEARNING HUB / CURRICULUM", description: "Follow structured routes from first principles to applied operations. Your next module is always one clear step away.", icon: BookOpen, stats: [["ACTIVE PATHS", "03"], ["MODULES READY", "24"], ["XP AVAILABLE", "+2,480"]], tabs: ["Overview", "Paths", "Rooms", "Skills"], cards: [{ icon: Layers3, title: "Cybersecurity Fundamentals", type: "LEARNING PATH", meta: "08 modules  •  26% complete", tone: "amber" }, { icon: Network, title: "Network Foundations", type: "ROOM COLLECTION", meta: "06 rooms  •  Beginner", tone: "cyan" }, { icon: Terminal, title: "Linux Operator Track", type: "LEARNING PATH", meta: "12 modules  •  Locked", tone: "green" }] },
  challenges: { title: "Challenges", eyebrow: "OPERATIONS / CHALLENGE INDEX", description: "A searchable challenge surface for the content you create. Filter by category, difficulty, and skill signal.", icon: Crosshair, stats: [["AVAILABLE", "12"], ["SOLVED", "12"], ["XP EARNED", "1,840"]], tabs: ["All challenges", "Web", "Network", "Linux"], cards: [{ icon: Code2, title: "SQL Injection Basics", type: "WEB  /  BEGINNER", meta: "+80 XP  •  15 min", tone: "amber" }, { icon: ShieldCheck, title: "Auth Boundary", type: "WEB  /  INTERMEDIATE", meta: "+140 XP  •  30 min", tone: "cyan" }, { icon: Terminal, title: "File Permissions", type: "LINUX  /  BEGINNER", meta: "+60 XP  •  10 min", tone: "green" }] },
  labs: { title: "Labs", eyebrow: "LABORATORY / ENVIRONMENT INDEX", description: "Spin up contained practice environments and keep the evidence of your investigation in one workspace.", icon: Database, stats: [["ACTIVE LABS", "01"], ["AVAILABLE", "08"], ["SESSION TIME", "42m"]], tabs: ["All labs", "Active", "Completed"], cards: [{ icon: Database, title: "Web Request Lab", type: "ACTIVE  /  WEB", meta: "12 min remaining  •  node 07", tone: "amber" }, { icon: Network, title: "Packet Trail Lab", type: "READY  /  NETWORK", meta: "+120 XP  •  Intermediate", tone: "cyan" }, { icon: Terminal, title: "Shell Fundamentals", type: "READY  /  LINUX", meta: "+60 XP  •  Beginner", tone: "green" }] },
  machines: { title: "Machines", eyebrow: "TARGETS / MACHINE INVENTORY", description: "A controlled view of target machines, their state, and the operator actions available in each session.", icon: Network, stats: [["ONLINE", "03"], ["YOUR SESSIONS", "01"], ["TARGETS", "09"]], tabs: ["All targets", "Running", "Archived"], cards: [{ icon: Network, title: "NODE-07 / Web Relay", type: "ONLINE  /  12ms", meta: "10.10.14.7  •  port 443", tone: "amber" }, { icon: ShieldCheck, title: "ARCHIVE-02 / Bastion", type: "LOCKED  /  REQUIRES PATH", meta: "Prerequisite: Linux", tone: "steel" }, { icon: Terminal, title: "LAB-03 / Shell", type: "AVAILABLE  /  8m", meta: "10.10.22.3  •  port 22", tone: "green" }] },
  academy: { title: "Academy", eyebrow: "ACADEMY / SKILL GRAPH", description: "See the skills behind the challenges. Discover prerequisites, track practice, and choose the next skill to strengthen.", icon: BrainCircuit, stats: [["DISCOVERED", "18"], ["PRACTICED", "07"], ["MASTERED", "02"]], tabs: ["Skill tree", "Categories", "Milestones"], cards: [{ icon: BrainCircuit, title: "Web Exploitation", type: "LEARNING  /  42%", meta: "3 prerequisites  •  04 challenges", tone: "amber" }, { icon: Network, title: "TCP / DNS / HTTP", type: "PRACTICED  /  71%", meta: "2 rooms  •  07 challenges", tone: "cyan" }, { icon: LockKeyhole, title: "Defensive Security", type: "LOCKED  /  00%", meta: "Prerequisite: Networking", tone: "steel" }] },
  paths: { title: "Learning Paths", eyebrow: "CURRICULUM / PATH BUILDER", description: "Move through deliberate sequences of rooms, challenges, and labs. Paths are designed to make progress visible.", icon: Layers3, stats: [["IN PROGRESS", "02"], ["COMPLETED", "01"], ["PATH XP", "3,420"]], tabs: ["My paths", "Explore", "Completed"], cards: [{ icon: Layers3, title: "Cybersecurity Fundamentals", type: "IN PROGRESS  /  26%", meta: "02 / 08 modules  •  +2,000 XP", tone: "amber" }, { icon: ShieldCheck, title: "Web Application Security", type: "AVAILABLE  /  00%", meta: "10 modules  •  Intermediate", tone: "cyan" }, { icon: Trophy, title: "Linux Operator", type: "COMPLETED  /  100%", meta: "06 modules  •  Certificate ready", tone: "green" }] },
  leaderboard: { title: "Leaderboard", eyebrow: "COMPETITION / SIGNAL RANKING", description: "Compare progress across the lab without losing sight of the work behind each number.", icon: Trophy, stats: [["YOUR RANK", "#042"], ["THIS WEEK", "+180 XP"], ["STREAK", "07 DAYS"]], tabs: ["Global", "Friends", "Weekly"], cards: [{ icon: Trophy, title: "01  /  ORBITAL", type: "MASTER  •  12,480 XP", meta: "+420 this week", tone: "amber" }, { icon: Users, title: "02  /  KERNELFOX", type: "OPERATOR  •  11,920 XP", meta: "+380 this week", tone: "cyan" }, { icon: Gauge, title: "042  /  NOVA", type: "LEARNER  •  1,840 XP", meta: "+180 this week", tone: "green" }] },
  terminal: { title: "Terminal", eyebrow: "TOOLS / BROWSER TERMINAL", description: "A terminal workspace for commands, output, and session context. Connect it to a lab when runtime services are enabled.", icon: Terminal, stats: [["SESSION", "READY"], ["SHELL", "BASH"], ["LATENCY", "12ms"]], tabs: ["Terminal", "History", "Sessions"], cards: [{ icon: Terminal, title: "node-07$", type: "READY  /  CONNECTED", meta: "Type a command to begin", tone: "green" }, { icon: FileText, title: "Last command history", type: "EMPTY  /  NEW SESSION", meta: "No commands recorded", tone: "steel" }] },
  notes: { title: "Notes", eyebrow: "TOOLS / OPERATOR NOTES", description: "Keep observations, commands, and evidence close to the operation. Notes are grouped by workspace and challenge.", icon: FileText, stats: [["NOTES", "00"], ["PINNED", "00"], ["STORAGE", "READY"]], tabs: ["All notes", "Pinned", "Recent"], cards: [{ icon: FileText, title: "No notes captured yet", type: "EMPTY WORKSPACE", meta: "Create a note from any operation", tone: "steel" }] },
  bookmarks: { title: "Bookmarks", eyebrow: "TOOLS / SAVED SIGNALS", description: "Save challenges, rooms, skills, and writeups for a later pass.", icon: LockKeyhole, stats: [["SAVED", "00"], ["CHALLENGES", "00"], ["ROOMS", "00"]], tabs: ["All saved", "Challenges", "Rooms"], cards: [{ icon: LockKeyhole, title: "Your saved signals will appear here", type: "EMPTY COLLECTION", meta: "Bookmark an item to build a queue", tone: "steel" }] },
  rooms: { title: "Rooms", eyebrow: "LEARN / ROOM INDEX", description: "Room frameworks combine theory, objectives, tasks, questions, resources, and completion in one focused surface.", icon: Database, stats: [["AVAILABLE", "06"], ["IN PROGRESS", "01"], ["COMPLETED", "02"]], tabs: ["All rooms", "In progress", "Completed"], cards: [{ icon: Network, title: "SQL Injection Fundamentals", type: "IN PROGRESS  /  80%", meta: "04 tasks remaining", tone: "amber" }, { icon: BookOpen, title: "HTTP Under the Hood", type: "AVAILABLE  /  BEGINNER", meta: "06 sections  •  +240 XP", tone: "cyan" }] },
  writeups: { title: "Writeups", eyebrow: "COMMUNITY / TECHNICAL ARCHIVE", description: "A structured archive for walkthroughs, mitigations, and the reasoning behind each solve.", icon: FileText, stats: [["PUBLISHED", "00"], ["DRAFTS", "00"], ["BOOKMARKS", "00"]], tabs: ["Latest", "My writeups", "Bookmarked"], cards: [{ icon: FileText, title: "No writeups published yet", type: "EMPTY ARCHIVE", meta: "Your future walkthroughs belong here", tone: "steel" }] },
  profile: { title: "Cyber Profile", eyebrow: "OPERATOR / PERSONAL PROFILE", description: "Your skill signal, activity, achievements, and learning identity in one place.", icon: Users, stats: [["LEVEL", "04"], ["XP", "1,840"], ["ACHIEVEMENTS", "03"]], tabs: ["Overview", "Activity", "Achievements"], cards: [{ icon: Trophy, title: "First Signal", type: "ACHIEVEMENT  /  UNLOCKED", meta: "Completed your first challenge", tone: "green" }, { icon: Zap, title: "Seven Day Signal", type: "STREAK  /  ACTIVE", meta: "Keep the chain alive", tone: "amber" }] },
  progress: { title: "Progress", eyebrow: "TELEMETRY / PERSONAL PROGRESS", description: "Detailed progress across XP, categories, streaks, completion rate, solve time, and hint usage.", icon: BarChart3, stats: [["XP", "1,840"], ["COMPLETION", "34.8%"], ["AVG SOLVE", "18m"]], tabs: ["Overview", "Categories", "Timeline"], cards: [{ icon: BarChart3, title: "Progress signal", type: "LAST 30 DAYS", meta: "+420 XP  •  +8.2% completion", tone: "amber" }, { icon: Activity, title: "Activity timeline", type: "07 EVENTS", meta: "Last active 12 minutes ago", tone: "cyan" }] },
  creator: { title: "Creator Studio", eyebrow: "STUDIO / CONTENT OPERATIONS", description: "Create and manage challenges, rooms, labs, paths, flags, hints, files, objectives, and prerequisites without editing source code.", icon: Settings2, stats: [["DRAFTS", "00"], ["PUBLISHED", "00"], ["CREATORS", "01"]], tabs: ["Overview", "Challenges", "Paths", "Analytics"], cards: [{ icon: Plus, title: "Create challenge", type: "BUILDER  /  READY", meta: "Define flags, hints, files, and objectives", tone: "amber" }, { icon: Layers3, title: "Create learning path", type: "BUILDER  /  READY", meta: "Sequence modules and prerequisites", tone: "cyan" }, { icon: BarChart3, title: "Content analytics", type: "ANALYTICS  /  READY", meta: "Measure completion and solve time", tone: "green" }] },
  competitions: { title: "Competitions", eyebrow: "EVENTS / COMPETITION CONTROL", description: "A home for timed events, scoring rules, teams, and live event status.", icon: Trophy, stats: [["LIVE EVENTS", "00"], ["UPCOMING", "01"], ["TEAMS", "00"]], tabs: ["Live", "Upcoming", "Archive"], cards: [{ icon: Trophy, title: "No live competition", type: "STANDBY", meta: "Create an event from Creator Studio", tone: "steel" }] },
  settings: { title: "Settings", eyebrow: "SYSTEM / CONFIGURATION", description: "Configure your profile, appearance, notifications, keyboard shortcuts, and workspace preferences.", icon: Settings2, stats: [["ACCOUNT", "READY"], ["THEME", "DARK"], ["SHORTCUTS", "ON"]], tabs: ["Profile", "Appearance", "Notifications", "Security"], cards: [{ icon: Settings2, title: "Workspace preferences", type: "CONFIGURATION", meta: "Theme, shortcuts, and notification rules", tone: "amber" }, { icon: ShieldCheck, title: "Security settings", type: "PROTECTED", meta: "Authentication and sessions", tone: "green" }] },
  status: { title: "System Status", eyebrow: "SYSTEM / SERVICE HEALTH", description: "Live service indicators for the RHZ LAB platform and its learning infrastructure.", icon: Activity, stats: [["SERVICES", "06/06"], ["UPTIME", "99.98%"], ["LATENCY", "12ms"]], tabs: ["Overview", "Incidents", "History"], cards: [{ icon: ShieldCheck, title: "All services nominal", type: "ONLINE  /  99.98%", meta: "Last check 12 seconds ago", tone: "green" }, { icon: Network, title: "Lab node 07", type: "ONLINE  /  12ms", meta: "No active incidents", tone: "cyan" }] },
};



export default function SectionPage({ section }: { section: string }) {
  const config = configs[section] ?? configs.learn;
  const [, navigate] = useLocation();
  const Icon = config.icon;
  const notify = (text: string) => toast(text, { description: "The interface is ready for your content and runtime services." });
  const nav = Object.keys(iconMap);
  return <div className="section-page"><header className="section-topbar"><Link href="/" className="back-link"><ArrowLeft size={16} /> RHZ LAB <span>/</span> COMMAND CENTER</Link><div className="section-top-actions"><button onClick={() => notify("Search opened")}><Search size={16} /> Search <kbd>⌘ K</kbd></button><button onClick={() => navigate("/settings")}><Settings2 size={16} /></button><div className="avatar">N<span>+</span></div></div></header><div className="section-layout"><aside className="section-rail"><div className="rail-brand"><div className="brand-mark"><img src="/manus-storage/rhz-lab-logo_9afda854.png" alt="RHZ LAB" /></div><div><strong>RHZ<span>LAB</span></strong><small>OPERATIONS</small></div></div><div className="section-rail-label mono">MODULES</div>{nav.map((label) => { const path = label === "Dashboard" ? "/" : `/${label.toLowerCase()}`; const active = path === `/${section}` || (section === "progress" && label === "Dashboard"); const NavIcon = iconMap[label as keyof typeof iconMap]; return <Link key={label} href={path} className={`section-nav-link ${active ? "active" : ""}`}><NavIcon size={15} /> {label}</Link>; })}<div className="section-rail-footer"><span className="pulse-dot" /> SYSTEM ONLINE</div></aside><main className="section-main"><div className="section-hero"><div><div className="eyebrow mono"><span className="status-dot amber" /> {config.eyebrow}</div><h1><Icon size={27} /> {config.title}</h1><p>{config.description}</p></div><button className="primary-button" onClick={() => notify(`${config.title} action opened`)}><Plus size={15} /> NEW OPERATION</button></div><div className="section-stats">{config.stats.map(([label, value]) => <div key={label} className="section-stat"><span className="mono">{label}</span><strong>{value}</strong></div>)}</div><div className="section-tabs">{config.tabs.map((tab, index) => <button key={tab} className={index === 0 ? "active" : ""} onClick={() => notify(`${tab} view selected`)}>{tab}</button>)}<div className="tab-spacer" /><button onClick={() => notify("Filters opened")}><Search size={15} /> FILTERS</button></div><div className="section-content-grid">{config.cards.map((card, index) => { const CardIcon = card.icon; return <button className="content-card" key={card.title} onClick={() => notify(`${card.title} selected`)}><div className={`content-card-icon ${card.tone}`}><CardIcon size={19} /></div><div className="content-card-body"><div className="mono content-card-type">{card.type}</div><h2>{card.title}</h2><p>{card.meta}</p></div><ChevronRight className="card-arrow" size={18} /></button>; })}</div><div className="empty-information"><CircleHelp size={17} /><div><strong>Creator-controlled content surface</strong><p>This page is wired for the platform infrastructure described in your brief. Challenge data, users, scoring, terminal sessions, and uploads require the backend/data layer to be connected next.</p></div><ArrowUpRight size={16} /></div></main></div></div>;
}
